"""Generate V6 scope + limitations statements from computed artifacts.

CORE RULE: every shipped number must be produced by a script. This script reads
the MODEL benchmark JSON (data/canonical/model_v6_benchmark.json) and emits a
tracked, regenerable scope/limitations document. It also refreshes the marked
"<!-- V6_SCOPE_AUTO -->" block in README.md and CLAUDE.md so the regional-drift
headline number is never hand-typed.

Folds in the audit findings:
  W1  regional calibration drift (pooled vs per-block AUC)        — from benchmark JSON
  W4/W5 in-AOI vs out-of-AOI scope                                — from benchmark JSON
  W10 temporal drift (2012-2014 soils vs recent NDMI)            — documented decision
  W11 30 m SCL water-mask + slope/TWI gaps                        — COVERAGE_FEASIBILITY.md verdict
  W12 10 m cascade re-evaluation trigger (valid-pixel n >= 30)    — COVERAGE_FEASIBILITY.md verdict
  2020/2021 out-of-period validation decision                     — VALIDATION_2020_2021_FEASIBILITY.md verdict

Run:  py -3.12 scripts/v6/generate_scope_statements.py
Deterministic: re-running yields byte-identical tracked artifacts.
"""
from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[2]
CANON = BASE / "data" / "canonical"
BENCH_JSON = CANON / "model_v6_benchmark.json"
OUT_SCOPE = CANON / "SCOPE_AND_LIMITATIONS_V6.md"
README = BASE / "README.md"
CLAUDE = BASE / "CLAUDE.md"

AUTO_BEGIN = "<!-- V6_SCOPE_AUTO -->"
AUTO_END = "<!-- /V6_SCOPE_AUTO -->"

# Re-evaluation trigger (COVERAGE_FEASIBILITY.md Q3 verdict) — single source of truth.
RETEST_VALID_PIXEL_N = 30


def _fmt(x) -> str:
    return "n/a" if x is None else (f"{x:.3f}" if isinstance(x, float) else str(x))


def build_scope() -> tuple[str, dict]:
    bench = json.loads(BENCH_JSON.read_text(encoding="utf-8"))
    m0 = next(m for m in bench["models"] if m["id"] == "M0")
    rec = bench["recommendation"]
    aoi = bench["aoi_split"]

    pooled = m0["pooled_spatial_auc"]
    perblk = m0["mean_per_block_spatial_auc"]
    loo = m0["loo_auc"]
    ci = m0["loo_auc_ci95"]
    in_aoi_auc = m0.get("aoi_stratified_auc", {}).get("in_aoi")
    out_aoi_auc = m0.get("aoi_stratified_auc", {}).get("out_of_aoi")
    n_in = aoi["n_in_aoi"]
    n_out = aoi["n_out_of_aoi"]

    facts = {
        "recommended_model": rec["recommended_model_id"],
        "pooled_auc": pooled,
        "per_block_auc": perblk,
        "loo_auc": loo,
        "n_in_aoi": n_in,
        "n_out_aoi": n_out,
        "retest_valid_pixel_n": RETEST_VALID_PIXEL_N,
    }

    # One-line headline reused in README/CLAUDE (numbers from JSON, never hand-typed).
    headline = (
        f"Shipped salinity anchor = **{rec['recommended_model_id']} (univariate NDMI logit)**, "
        f"LOO AUC {_fmt(loo)} (CI [{_fmt(ci[0])}, {_fmt(ci[1])}]). "
        f"**Regional calibration drift (W1):** pooled spatial AUC {_fmt(pooled)} vs per-block {_fmt(perblk)} "
        f"— the model ranks salinity *locally* but absolute level must be calibrated per region."
    )

    L = []
    L += [
        "# V6 — Scope & Known Limitations (auto-generated)",
        "",
        "> Generated by `scripts/v6/generate_scope_statements.py` from "
        "`model_v6_benchmark.json` + the audit verdicts — do NOT hand-edit. "
        "Re-running yields a byte-identical file.",
        "",
        "## Headline",
        "",
        headline,
        "",
        "## W1 — Regional calibration drift (FIRST-CLASS scope statement)",
        "",
        f"- Pooled spatial leave-block-out AUC: **{_fmt(pooled)}**.",
        f"- Mean per-block spatial AUC: **{_fmt(perblk)}**.",
        "- The large pooled<per-block gap means between-region base-rate differences dominate the "
        "pooled metric. Cross-region suitability *ranking* is unreliable; within-region ranking is sound. "
        "This is a calibration-scope limitation, not loss of signal.",
        "",
        "## W4/W5 — In-AOI vs out-of-AOI skill (do not conflate training with test)",
        "",
        f"- The seabed AOI is defined by the 1960 Aral footprint polygon (NOT the all-True `in_aoi` column).",
        f"- In-AOI (seabed) pits: **{n_in}**; out-of-AOI (wider Priaralye, training domain): **{n_out}**.",
        f"- Baseline in-AOI LOO AUC: **{_fmt(in_aoi_auc)}**; out-of-AOI LOO AUC: **{_fmt(out_aoi_auc)}**.",
        f"- The {n_out} out-of-AOI pits are TRAINING data for the mapped seabed target and must NOT be "
        "counted as independent validation. In-AOI skill is the honest test metric (small n — directional).",
        "",
        "## W10 — Temporal drift / calibration vintage",
        "",
        "- Soil labels are 2012-2014 lab profiles (Pachikin/Kozybaeva); the NDMI composite is recent. "
        "The NDMI<->salinity relation is assumed quasi-stationary. No contemporaneous re-sampling exists "
        "to verify stationarity — treat the map as a screening aid, re-validate if recent ground truth appears.",
        "",
        "## W11 — Sensor-coverage gaps (COVERAGE_FEASIBILITY.md verdict)",
        "",
        "- 30 m SCL water mask: feasible only with GEE reprocessing (owner action) — not in-repo today.",
        "- 30 m slope/TWI: only ~33% finite at 30 m; full restoration unlikely in-repo (no slope gate at 30 m).",
        "- These gaps are why V6 lives on the 30 m stack as a salinity screen, not a full physical zoning.",
        "",
        "## W12 — 10 m cascade re-evaluation trigger",
        "",
        f"- Re-test the 10 m cascade when valid-pixel n >= **{RETEST_VALID_PIXEL_N}** "
        "(COVERAGE_FEASIBILITY.md Q3). Below that, the 10 m path is too sparse to evaluate honestly.",
        "",
        "## 2020/2021 out-of-period data (VALIDATION_2020_2021_FEASIBILITY.md verdict)",
        "",
        "- DECISION: the 2020/2021 campaign **cannot** be wired into the V6 pipeline now (pit IDs do not "
        "align across files; distinct ID schemes). It has modest value only as a **conservative out-of-period "
        "check** with strict period separation. It is **NOT merged** into the 2012-2014 training labels.",
        "",
        "## Anti-patterns held (must not regress)",
        "",
        "- suitability = 1 - P(saline); the exploratory NDMI+MSAVI->saxaul classifier is NOT a decision model.",
        "- Salinity model independent of saxaul labels (no circularity).",
        "- Every AUC carries a held-out bootstrap CI; raw AUC + direction reported.",
        "",
    ]
    return "\n".join(L), facts, headline


def patch_marked_block(path: Path, headline: str) -> bool:
    """Replace the content between AUTO_BEGIN/END markers; insert the block if absent."""
    text = path.read_text(encoding="utf-8")
    block = (
        f"{AUTO_BEGIN}\n"
        f"> **V6 scope (auto-generated — see `data/canonical/SCOPE_AND_LIMITATIONS_V6.md`):** {headline}\n"
        f"{AUTO_END}"
    )
    if AUTO_BEGIN in text and AUTO_END in text:
        pre = text.split(AUTO_BEGIN)[0]
        post = text.split(AUTO_END, 1)[1]
        new = pre + block + post
    else:
        # append near the V6 section if present, else at EOF
        new = text.rstrip() + "\n\n" + block + "\n"
    if new != text:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def main() -> None:
    scope_md, facts, headline = build_scope()
    OUT_SCOPE.write_text(scope_md, encoding="utf-8")
    print(f"Wrote {OUT_SCOPE.relative_to(BASE)}")
    for p in (README, CLAUDE):
        changed = patch_marked_block(p, headline)
        print(f"{'updated' if changed else 'unchanged'}: {p.name}")
    print("Facts:", json.dumps(facts, ensure_ascii=False))


if __name__ == "__main__":
    main()
